"""Added missing is_active column to guard table

Revision ID: 58914c3b8f9e
Revises: 8fd2d98025b2
Create Date: 2025-10-06 22:42:00.147767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58914c3b8f9e'
down_revision = '8fd2d98025b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('resigned_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('guard', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('resigned_date')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
