"""initial

Revision ID: 8fd2d98025b2
Revises: 
Create Date: 2025-10-04 07:22:52.940064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd2d98025b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_deadline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=10), nullable=False),
    sa.Column('expected_submission_time', sa.DateTime(), nullable=False),
    sa.Column('actual_submission_time', sa.DateTime(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=True),
    sa.Column('is_overdue', sa.Boolean(), nullable=True),
    sa.Column('reminder_30min_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_2hour_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_username', sa.String(length=50), nullable=False),
    sa.Column('recipient_role', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('day_shift_reminder_time', sa.String(length=5), nullable=True),
    sa.Column('night_shift_reminder_time', sa.String(length=5), nullable=True),
    sa.Column('overdue_reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('urgent_reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('notify_new_requests', sa.Boolean(), nullable=True),
    sa.Column('notify_attendance_submitted', sa.Boolean(), nullable=True),
    sa.Column('notify_attendance_missing', sa.Boolean(), nullable=True),
    sa.Column('notify_guard_issues', sa.Boolean(), nullable=True),
    sa.Column('notify_shift_changes', sa.Boolean(), nullable=True),
    sa.Column('in_app_notifications', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('is_accessible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('shift_type', sa.String(length=10), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('shift', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('marked_by', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guard_id'], ['guard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guard_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['guard_id'], ['guard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('scheduled_shift', sa.String(length=10), nullable=False),
    sa.Column('actual_shift', sa.String(length=10), nullable=False),
    sa.Column('scheduled_location_id', sa.Integer(), nullable=True),
    sa.Column('actual_location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('is_overtime', sa.Boolean(), nullable=True),
    sa.Column('is_shift_differential', sa.Boolean(), nullable=True),
    sa.Column('is_location_premium', sa.Boolean(), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=True),
    sa.Column('total_pay', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actual_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['guard_id'], ['guard.id'], ),
    sa.ForeignKeyConstraint(['scheduled_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('original_shift', sa.String(length=10), nullable=False),
    sa.Column('override_shift', sa.String(length=10), nullable=False),
    sa.Column('original_location_id', sa.Integer(), nullable=True),
    sa.Column('override_location_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['guard_id'], ['guard.id'], ),
    sa.ForeignKeyConstraint(['original_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['override_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_override')
    op.drop_table('payroll_tracking')
    op.drop_table('guard_comment')
    op.drop_table('attendance')
    op.drop_table('guard')
    op.drop_table('location')
    op.drop_table('user')
    op.drop_table('request')
    op.drop_table('notification_settings')
    op.drop_table('notification')
    op.drop_table('company')
    op.drop_table('attendance_deadline')
    # ### end Alembic commands ###
